FROM python:3.12-slim

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY api.py .
COPY database.py .
COPY index.html .
COPY style.css .
COPY app.js .
COPY sw.js .
COPY manifest.json .
COPY robots.txt .
COPY sitemap.xml .
COPY icon-192.png .
COPY icon-512.png .
COPY cs-index.html .
COPY cs-styles.css .
COPY cs-app.js .
COPY cs-manifest.json .
COPY cs-sw.js .
COPY cs-icon-192.png .
COPY cs-icon-512.png .

EXPOSE 8000